version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
           name: Install Blender
           environment:
            BLENDER_MAJOR: 2.79
            BLENDER_VERSION: 2.79
            GLIBC_VERSION: 219
           command: |
             curl -Ls http://mirror.cs.umn.edu/blender.org/release/Blender$BLENDER_MAJOR/blender-$BLENDER_VERSION-linux-glibc$GLIBC_VERSION-x86_64.tar.bz2 | sudo tar -xjv -C /opt/
             sudo ln -s /opt/blender-${BLENDER_VERSION}-linux-glibc${GLIBC_VERSION}-x86_64/blender /usr/local/bin/blender
       - run:
           name: Install Python3.6
           command: |
             sudo apt-get update
             sudo apt-get install software-properties-common libglu1
             sudo add-apt-repository -y ppa:deadsnakes/ppa
             sudo apt-get update
             sudo apt-get install python3.6 python3.6-dev python3.6-venv
       - run:
           name: Prepare venv with requirements
           command: |
             python3.6 -m venv .venv
             . .venv/bin/activate
             pip install -r requirements.txt -r requirements-lint.txt
             pip install -r image/golem_blender_app/requirements.txt
       - run:
           name: Run setup.py develop
           command: |
             . .venv/bin/activate
             cd image/golem_blender_app/ && python setup.py develop && cd -
       - run:
           name: Check versions
           command: |
             . .venv/bin/activate
             echo $PATH
             python --version || echo "no python"
             pip --version || echo "no pip"
             docker --version || echo "no docker"
             blender --version || echo "no blender"
       - run:
           name: Build docker image
           command: |
             docker build --tag blenderapp_test image
           no_output_timeout: 15m
       - run:
           name: Run tests
           command: |
             . .venv/bin/activate
             python -m pytest
       - run:
           name: Run linters
           command: |
             . .venv/bin/activate
             pylint -rn image/golem_blender_app/golem_blender_app
             pylint -rn tests
             flake8 image/golem_blender_app/golem_blender_app
             flake8 tests
             mypy image/golem_blender_app/golem_blender_app
             mypy tests
       - run:
           name: Inspect Docker image size
           command: |
             docker images blenderapp_test
